### ISSUE TITLE
What is the practical difference?

### ISSUE THREAD

**Issue by christian-schlichtherle** [itplr-kosit/validator-configuration-xrechnung#32]
Between...

https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/1e62a804f8c3d049be6b1e5ffc405fdb8891f777/scenarios.xml#L76

and...

    <acceptMatch>/rep:report[@valid='true']</acceptMatch>

It seems the latter is a bit more concise.

**Comment by rkottmann** [comment]
The difference is the whole difference why the validator exists:  `/rep:report[@valid='true']` is about the technical validation results (XSD and schematron errors) and the `<acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>` is about  the result of computing  an `rep:accept` recomendation based on the technical validation results and the customizations of severity levels in scenario.xml. 

Hope this answers your question. Otherwise, pls feel free to re-open.

**Comment by christian-schlichtherle** [comment]
So if the severity levels are not customized, then the following holds true?

    exists(/rep:report[@valid='true']) = exists(/rep:report/rep:assessment[1]/rep:accept[1])

**Comment by rkottmann** [comment]
yes
