### ISSUE TITLE
validationtool-1.4.1 mit validator-configuration-xrechnung_2.0.1 meldet Fehler "[BR-DE-18] Skonto/Verzug Zeilen"

### ISSUE THREAD

**Issue by spacetrack** [itplr-kosit/validator-configuration-xrechnung#54]
Hallo,

obwohl die Zeile

```
  <cac:PaymentTerms>
    <cbc:Note>#SKONTO#TAGE=14#PROZENT=0.00#BASISBETRAG=9371.25#</cbc:Note>
  </cac:PaymentTerms>
```

in meinen Augen richtig aussieht, wird im Prüfbericht die Fehlermeldung

> [BR-DE-18] Skonto/Verzug Zeilen in CreditNote muessen diesem regulaerem Ausdruck entsprechen: #(SKONTO|VERZUG)#TAGE=([0-9]+#PROZENT=[0-9]+\.[0-9]{2})(#BASISBETRAG=-?[0-9]+\.[0-9]{2})?#$.Die Informationen zur Gewährung von Skonto oder zur Berechnung von Verzugszinsen (...)

ausgegeben.

Auch der Online-Validator "regex101" meint, dies sei ein "Full match": [https://regex101.com/r/9GcDE8/2](https://regex101.com/r/9GcDE8/2).

Der validationtool-1.4.0 mit validator-configuration-xrechnung_2.0.0 beanstandet die Zeile nicht.

Mach' ich etwas falsch?

Viele Grüße
Björn Winkler

**Comment by marvindoering** [comment]
Hi spacetrack,

try a line break after the last #. That fixed it for me, \r\n

BR
Marvin

**Comment by LordPinhead** [comment]
The Regex is wrong, don´t worry. The $ is the problem, because the line does not END here, you have the end-tag following.

Working example:
http://regexstorm.net/tester?p=%23%28SKONTO%7cVERZUG%29%23TAGE%3d%28%5b0-9%5d%2b%23PROZENT%3d%5b0-9%5d%2b%5c.%5b0-9%5d%7b2%7d%29%28%23BASISBETRAG%3d-%3f%5b0-9%5d%2b%5c.%5b0-9%5d%7b2%7d%29%3f%23&i=%3ccbc%3aNote%3e%23SKONTO%23TAGE%3d14%23PROZENT%3d0.00%23BASISBETRAG%3d9371.25%23%3c%2fcbc%3aNote%3e

to match the line, you could either remove the $ of the regex or change it to:

(<cbc:Note>)#(SKONTO|VERZUG)#TAGE=([0-9]+#PROZENT=[0-9]+\.[0-9]{2})(#BASISBETRAG=-?[0-9]+\.[0-9]{2})?#(</cbc:Note>)$
