### ISSUE TITLE
Schematron directory in configuration 2.0.1-zip missing

### ISSUE THREAD

**Issue by HCC-RSch** [itplr-kosit/validator-configuration-xrechnung#61]
In the validator-conf-zip-file version 2.0.1 the schematron directory is missing.

**Comment by phax** [comment]
Correct, the release file 
https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/download/release-2020-12-31/validator-configuration-xrechnung_2.0.1_2020-12-31.zip does not contain the Schematrons.
The reason is simple: to apply Schematron rules, you need to convert them to XSLT and to save you this effort, the release package only contains the pre-compiled XSLTs.

The source Schematrons are available from the separate link https://github.com/itplr-kosit/xrechnung-schematron/releases/tag/release-1.5.0

hth

**Comment by HCC-RSch** [comment]
I'm not sure if I've really got it, but of course I close the issue.

**Comment by phax** [comment]
Here's a short explanation what happens when you want to apply Schematron:
1. The .SCH file is converted via (3 different) predefined XSLTs to a new .XSLT file - that sounds weird but that is what happens
2. The created .XSLT file from step 1 is applied onto the XML document to be validated and created "SVRL" (the Schematron Validation Result Language)
3. This SVRL is interpreted to get the errors/warnings from validation

To avoid that step 1 needs to be executed by everyone, the Download-Package only contains the XSLT.

Hope that clarifies it a bit
